version: '3'
services:
  ext-server:
    container_name: u2u-server
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '12345:8888'
      - '5556:5555'
    volumes:
      - ../logs/u2u-marketplace-api:/usr/src/app/u2u-server/logs
    networks:
      - u2u-nw
    # logging:
    #   driver: gcplogs
    #   options:
    #     gcp-project: web-team-380004
  redis:
    image: redis
    command: >
      --requirepass u2umarketplace
    networks:
      - u2u-nw
    volumes:
      - redis-data:/data
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: BbbksIcxadJwQ8
      POSTGRES_DB: local-marketplace
    networks:
      - u2u-nw
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
networks:
  u2u-nw:
    external: false
    name: u2u-nw
volumes:
  redis-data: