version: '3'
services:
  # redis:
  #   image: redis
  #   command: >
  #     --requirepass ${REDIS_PASSWORD}
  #   ports:
  #     - '6379:6379'
  #   networks:
  #     - vucar-nw
  #   volumes:
  #     - redis-data:/data
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache:/data
    networks:
      - vucar-nw
  ext-server:
    container_name: vucar-server
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - cache
    restart: always
    ports:
      - '8888:8888'
      - '5555:5555'
    volumes:
      - ./:/app
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECOND_DATABASE_URL: ${SECOND_DATABASE_URL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_SECRET: ${GOOGLE_SECRET}
      ACCESS_KEY: ${ACCESS_KEY}
      SECRET: ${SECRET}
      GOOGLE_EMAIL_USERNAME: ${GOOGLE_EMAIL_USERNAME}
      GOOGLE_EMAIL_PASSWORD: ${GOOGLE_EMAIL_PASSWORD}
      REDIS_CLUSTER_NODE: ${REDIS_CLUSTER_NODE}
      REDIS_CLUSTER: ${REDIS_CLUSTER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PREFIX: ${REDIS_PREFIX}
      REDISDB_HOST: ${REDISDB_HOST}
      REDISDB_PORT: ${REDISDB_PORT}
      BUCKET_NAME: ${BUCKET_NAME}
      CDN_URL: ${CDN_URL}
      REBRANDER_UPLOAD_KEY: ${REBRANDER_UPLOAD_KEY}
      WEBHOOK_API_KEY: ${WEBHOOK_API_KEY}
      REBRANDER_URL: ${REBRANDER_URL}
      XEZII_URL: ${XEZII_URL}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      PLAUSIBLE_URL: ${PLAUSIBLE_URL}
      PLAUSIBLE_TOKEN: ${PLAUSIBLE_TOKEN}
      VAP_URL: ${VAP_URL}
      CASSO_KEY: ${CASSO_KEY}
      ZALO_APP_ID: ${ZALO_APP_ID}
      ZALO_SECRET_KEY: ${ZALO_SECRET_KEY}
      GOOGLE_AUTH_REDIRECT: ${GOOGLE_AUTH_REDIRECT}
      # GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
    networks:
      - vucar-nw
networks:
  vucar-nw:
    external: false
    name: vucar-nw
volumes:
  cache:
    driver: local
