name: CI/CD Pipeline

on:
  push:
    branches:
      - 'master'
      - 'staging'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH and deploy to staging
      if: github.ref == 'refs/heads/staging'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.GCP_VM_IP }}
        username: ${{ secrets.GCP_VM_USERNAME }}
        key: ${{ secrets.GCP_VM_PRIVATE_KEY }}
        script: /home/dangk/vucar-backend-prisma/deploy-staging.sh
        node-version: "16"

    - name: SSH and deploy to production
      if: github.ref == 'refs/heads/master'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.GCP_VM_IP }}
        username: ${{ secrets.GCP_VM_USERNAME }}
        key: ${{ secrets.GCP_VM_PRIVATE_KEY }}
        script: /home/dangk/vucar-backend-prisma/deploy-production.sh
        node-version: "16"
